#!/usr/bin/env bash
# This script displays information from /etc/passwd in a story format
while IFS=: read -r username password userid groupid user_info home_dir shell
do
    echo "The user $username is part of the $groupid gang, lives in $home_dir and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $user_info"
done < /etc/passwd
