#!/usr/bin/env bash
# Displays Best School 10 times, with "Hi" after the 9th iteration
n=1
while [ "$n" -le 10 ]
do
    echo "Best School"
    if [ "$n" -eq 9 ]
    then
        echo "Hi"
    fi
    n=$((n + 1))
done
