#!/usr/bin/env bash
# Displays numbers 1-20 with bad luck messages using a case statement
n=1
while [ "$n" -le 20 ]
do
    echo "$n"
    case "$n" in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
    esac
    n=$((n + 1))
done
