#!/usr/bin/env bash
# Displays PID and name of processes containing bash
for pid in /proc/[0-9]*; do
    cmd=$(cat "$pid/comm" 2>/dev/null)
    if [[ $cmd == *bash* ]]; then
        echo "$(basename "$pid") $cmd"
    fi
done

